# åŸºæœ¬ã¯ github.com ã®ãƒ¬ãƒã‚¸ãƒˆãƒªãƒ¼ã‚’æŒ‡å®šã™ã‚‹ã ã‘
[[plugins]]
repo = 'Shougo/dein.vim'

## git clone å¾Œã€å®Ÿè¡Œã™ã¹ãã‚³ãƒãƒ³ãƒ‰ãŒã‚ã‚‹å ´åˆã¯ã“ã‚“ãªæ„Ÿã˜
#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#hook_post_update = '''
#  if dein#util#_is_windows()
#    let cmd = 'tools\\update-dll-mingw'
#  elseif dein#util#_is_cygwin()
#    let cmd = 'make -f make_cygwin.mak'
#  elseif executable('gmake')
#    let cmd = 'gmake'
#  else
#    let cmd = 'make'
#  endif
#  let g:dein#plugin.build = cmd
#'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'sjl/gundo.vim'

[[plugins]]
repo = 'vim-scripts/quickfixstatus.vim'

[[plugins]]
repo = 'vim-scripts/hier'

[[plugins]]
repo = 'vim-scripts/quickrun.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'Shougo/unite-outline'

#[[plugins]]
#repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-scripts/quickhl.vim'
#""NeoBundle 'aharisu/vim_goshrepl'
#""NeoBundle 'mitechie/pyflakes-pathogen'
#""NeoBundle 'sontek/rope-vim'
#""NeoBundle 'VimClojure'
#""NeoBundle 'javacomplete'

#[[plugins]]
#repo = 'hewes/unite-gtags'
#""NeoBundle 'thinca/vim-editvar'

#[[plugins]]
#repo = 'ujihisa/unite-launch'

[[plugins]]
repo = 'bling/vim-airline'
#""NeoBundle 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'junegunn/vim-easy-align'
#"
#""NeoBundle "osyo-manga/unite-quickfix"
#""NeoBundle "osyo-manga/shabadou.vim"
#""NeoBundle 'bufferlist.vim'
#""NeoBundle 'aharisu/Gauche-Complete'
#""NeoBundle 'Pydiction'
#""NeoBundle 'pythoncomplete'

#[[plugins]]
#repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'luochen1990/rainbow'
#""NeoBundle 'slimv.vim'
#""NeoBundle 'guns/vim-clojure-static'

[[plugins]]
repo = 'supasorn/vim-easymotion'
#""NeoBundle 'tpope/vim-fireplace'

[[plugins]]
repo = 'tpope/vim-surround'
#"" redl $B$NJd405!G=$,=E$$(B
#""NeoBundle 'dgrnbrg/vim-redl'
#""NeoBundle 'kovisoft/slimv'
#""NeoBundle 'ivanov/vim-ipython'
#""NeoBundle 'jpalardy/vim-slime'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'djoshea/vim-autoread'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rbonvall/vim-textobj-latex'

#[[plugins]]
#repo = 'lervag/vim-latex'

[[plugins]]
repo = 'igrep/vim-latex-omnifunc'

[[plugins]]
repo = 'Raimondi/delimitMate'

[[plugins]]
repo = 'JuliaLang/julia-vim'

[[plugins]]
repo = 'Shougo/junkfile.vim'

#[[plugins]]
#repo = 'jceb/vim-orgmode'

#[[plugins]]
#repo = "hdima/python-syntax"

#""NeoBundle "nvie/vim-flake8"

#[[plugins]]
#repo = "hynek/vim-python-pep8-indent"

[[plugins]]
repo = 'kana/vim-textobj-indent'

#[[plugins]]
#repo = 'bps/vim-textobj-python'

#[[plugins]]
#repo = "alfredodeza/khuno.vim"

[[plugins]]
repo = "rhysd/clever-f.vim"

#[[plugins]]
#repo = "tacroe/unite-mark"

[[plugins]]
repo = 'jacquesbh/vim-showmarks'

#[[plugins]]
#repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
repo = 'epeli/slimux'

#[[plugins]]
#repo = 'jalcine/cmake.vim'
#""NeoBundle 'tyru/eskk.vim'
#""NeoBundle 'haya14busa/incsearch.vim'

#[[plugins]]
#repo = 'lervag/vimtex'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = "zchee/deoplete-clang"

[[plugins]]
repo = "Shougo/neoinclude.vim"

[[plugins]]
repo = "xolox/vim-misc"

[[plugins]]
repo = "xolox/vim-notes"

[[plugins]]
repo = "ludovicchabant/vim-gutentags"

[[plugins]]
repo = "justmao945/vim-clang"

[[plugins]]
repo = "derekwyatt/vim-fswitch"

[[plugins]]
repo = "octol/vim-cpp-enhanced-highlight"

# ---- typescript ----
[[plugins]]
repo = "leafgarland/typescript-vim"
# ----

[[plugins]]
repo = "w0rp/ale"

# comment out
[[plugins]]
repo = "tpope/vim-commentary"
